[package]
name = "eztoml"
entry = "main.bend"

[tools.bolt]
git = "https://github.com/Emerging-Patterns/bolt"
rev = "38da7d930a9251f44cf7434032e954b2e706564b"
tag = "v1.7.0"
root = "."
narHash = "sha256-XaBdAuxtVDPZO4KzQA0V3s6qK1nwS7dS1gYAoXRVLxM="
